# Generated by Django 5.2.7 on 2026-08-19 12:02

import django.contrib.postgres.fields
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HQMember',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='hq_member', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=255)),
                ('sub_role', models.CharField(default='support', max_length=40)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'hq_members',
            },
        ),
        migrations.CreateModel(
            name='HQRole',
            fields=[
                ('key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=120)),
                ('builtin', models.BooleanField(default=False)),
                ('permissions', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=60), blank=True, default=list, size=None)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'hq_roles',
            },
        ),
        migrations.CreateModel(
            name='PendingInvitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('hq_member', 'HQ member'), ('school_teacher', 'School teacher')], max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('role_detail', models.CharField(blank=True, max_length=60)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'pending_invitations',
            },
        ),
    ]
