# Generated by Django 5.2.7 on 2026-08-19 12:02

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('present', 'Present'), ('no_show', 'No-show')], default='present', max_length=20)),
                ('marked_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'attendance',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('access_source', models.CharField(choices=[('subscription', 'Subscription'), ('package', 'Package'), ('free_lesson', 'Free lesson')], default='package', max_length=20)),
                ('credits_deducted', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('attended', 'Attended'), ('no_show', 'No-show')], default='confirmed', max_length=20)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_type', models.CharField(blank=True, choices=[('within_policy', 'Within policy'), ('outside_policy', 'Outside policy')], max_length=20)),
                ('credit_refunded', models.BooleanField(default=False)),
                ('booked_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'bookings',
            },
        ),
    ]
