# Generated by Django 5.2.7 on 2026-08-23 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='credits_deducted',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=6),
        ),
    ]
