# Generated by Django 5.2.7 on 2026-09-20 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_booking_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='access_source',
            field=models.CharField(choices=[('subscription', 'Subscription'), ('package', 'Package'), ('free_lesson', 'Free lesson'), ('event', 'Special event (no credits)')], default='package', max_length=20),
        ),
    ]
