# Generated by Django 5.2.7 on 2026-09-27 08:31

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_special_events'),
        ('catalog', '0022_course_slug'),
        ('schools', '0012_schoolclosure_excluded_packages'),
        ('students', '0014_studentpackageextension'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonSpotAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spot_alerts', to='catalog.lesson')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spot_alerts', to='schools.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spot_alerts', to='students.student')),
            ],
            options={
                'db_table': 'lesson_spot_alerts',
                'constraints': [models.UniqueConstraint(fields=('student', 'lesson'), name='uniq_spot_alert_student_lesson')],
            },
        ),
    ]
