# Generated by Django 5.2.7 on 2026-08-23 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_student_ical_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentpackage',
            name='starts_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
