# Generated by Django 5.2.7 on 2026-08-23 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_studentpackage_starts_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manualcreditgrant',
            name='amount',
            field=models.DecimalField(decimal_places=1, max_digits=6),
        ),
        migrations.AlterField(
            model_name='studentpackage',
            name='credits_remaining',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='studentpackage',
            name='credits_total',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=6),
        ),
    ]
