# Generated by Django 5.2.7 on 2026-09-07 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_student_postal_code_student_province'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdocument',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('valid', 'Valid'), ('expiring', 'Expiring'), ('expired', 'Expired'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
