# Generated by Django 5.2.7 on 2026-09-19 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0011_exhaust_drained_packages'),
    ]

    operations = [
        migrations.AddField(
            model_name='manualcreditgrant',
            name='kind',
            field=models.CharField(choices=[('grant', 'Grant'), ('deduction', 'Deduction'), ('reversal', 'Reversal')], default='grant', max_length=12),
        ),
        migrations.AddField(
            model_name='manualcreditgrant',
            name='reverses',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversed_by', to='students.manualcreditgrant'),
        ),
    ]
