# Generated by Django 5.2.7 on 2026-09-19 17:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0012_manualcreditgrant_kind_reverses'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='studentpackage',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentpackage',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='studentpackage',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('exhausted', 'Exhausted'), ('deleted', 'Deleted')], default='active', max_length=20),
        ),
    ]
