# Generated by Django 5.2.7 on 2026-09-21 09:22

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0011_schoolclosure_extends_packages'),
        ('students', '0013_studentpackage_deleted'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentPackageExtension',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('kind', models.CharField(choices=[('closure', 'School closure'), ('manual', 'Manual')], max_length=12)),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('days', models.IntegerField()),
                ('expires_before', models.DateTimeField()),
                ('expires_after', models.DateTimeField()),
                ('note', models.TextField(blank=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('closure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='package_extensions', to='schools.schoolclosure')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_extensions', to='schools.school')),
                ('student_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extensions', to='students.studentpackage')),
            ],
            options={
                'db_table': 'student_package_extensions',
                'constraints': [models.UniqueConstraint(condition=models.Q(('closure__isnull', False), ('revoked_at__isnull', True)), fields=('student_package', 'closure'), name='uniq_live_closure_extension_per_package')],
            },
        ),
    ]
