# Generated by Django 5.2.7 on 2026-08-19 22:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_initial'),
        ('schools', '0003_school_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='schools.school'),
        ),
    ]
