# Generated by Django 5.2.7 on 2026-08-23 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_package_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='language',
            field=models.CharField(default='it', max_length=8),
        ),
    ]
