# Generated by Django 5.2.7 on 2026-08-23 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_course_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='allowed_lesson_types',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='package',
            name='is_unlimited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='package',
            name='mode_filter',
            field=models.CharField(choices=[('all', 'All'), ('online', 'Online only'), ('in_person', 'In person only')], default='all', max_length=10),
        ),
        migrations.AddField(
            model_name='package',
            name='weekly_booking_cap',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
