# Generated by Django 5.2.7 on 2026-08-23 10:13
# Convert the legacy single-value lesson_type_restriction into the new
# allowed_lesson_types list ("all"/"" → [] = no restriction).

from django.db import migrations


def forwards(apps, schema_editor):
    Package = apps.get_model("catalog", "Package")
    for pkg in Package.objects.exclude(lesson_type_restriction__in=["", "all"]):
        pkg.allowed_lesson_types = [pkg.lesson_type_restriction]
        pkg.save(update_fields=["allowed_lesson_types"])


def backwards(apps, schema_editor):
    pass  # allowed_lesson_types simply disappears with the schema rollback


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_package_allowed_lesson_types_package_is_unlimited_and_more'),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]
