# Generated by Django 5.2.7 on 2026-08-23 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_backfill_allowed_lesson_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='credit_cost',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=5),
        ),
        migrations.AlterField(
            model_name='package',
            name='credits',
            field=models.DecimalField(decimal_places=1, default=10, max_digits=6),
        ),
    ]
