# Generated by Django 5.2.7 on 2026-08-23 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_alter_course_credit_cost_alter_package_credits'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='validity_unit',
            field=models.CharField(choices=[('days', 'Days'), ('months', 'Months')], default='days', max_length=10),
        ),
    ]
