# Generated by Django 5.2.7 on 2026-08-23 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_package_validity_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='description_es',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='package',
            name='description_fr',
            field=models.TextField(blank=True),
        ),
    ]
