# Generated by Django 5.2.7 on 2026-08-29 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_lesson_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='is_drop_in',
            field=models.BooleanField(default=False),
        ),
    ]
