# Generated by Django 5.2.7 on 2026-08-29 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_package_is_drop_in'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='package',
            options={'ordering': [models.OrderBy(models.F('sort_order'), nulls_last=True), 'price']},
        ),
        migrations.AddField(
            model_name='package',
            name='sort_order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
