# Generated by Django 5.2.7 on 2026-08-30 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_drop_cancelled_attendance_status'),
        ('teachers', '0003_teacher_first_name_teacher_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='compensation_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='teachers.compensationplan'),
        ),
    ]
