# Generated by Django 5.2.7 on 2026-09-08 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_course_lesson_email_info'),
        ('schools', '0006_backfill_school_owner_membership'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='attendancestatus',
            constraint=models.UniqueConstraint(fields=('school', 'name'), name='uniq_school_attendance_status_name'),
        ),
    ]
