# Generated by Django 5.2.7 on 2026-09-14 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_attendancestatus_uniq_school_attendance_status_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='internal_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='lesson',
            name='internal_notes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
