# Generated by Django 5.2.7 on 2026-09-20 08:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0018_course_lesson_internal_notes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='event_changed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='event_review_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='course',
            name='event_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='event_reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='course',
            name='event_status',
            field=models.CharField(blank=True, choices=[('draft', 'Draft'), ('pending', 'Pending HQ approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('suspended', 'Suspended by HQ'), ('cancelled', 'Cancelled by the school')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='course',
            name='event_submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='is_special_event',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='course',
            name='video_url',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='package',
            name='event',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_package', to='catalog.course'),
        ),
    ]
