# Generated by Django 5.2.7 on 2026-08-19 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='type',
            field=models.CharField(choices=[('hq_school', 'HQ ↔ School'), ('school_student', 'School ↔ Student'), ('school_teacher', 'School ↔ Teacher'), ('teacher_support', 'Teacher support')], default='school_student', max_length=20),
        ),
    ]
