# Generated by Django 5.2.7 on 2026-08-19 12:02

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('schools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompensationPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.CharField(max_length=255)),
                ('base_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('bonus_threshold', models.IntegerField(blank=True, null=True)),
                ('bonus_per_student', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('bonus_max_threshold', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compensation_plans', to='schools.school')),
            ],
            options={
                'db_table': 'compensation_plans',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('bio', models.TextField(blank=True)),
                ('photo_url', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'teachers',
            },
        ),
        migrations.CreateModel(
            name='CompensationPlanRate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('base_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('bonus_per_student', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('lesson_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='catalog.lessontype')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='teachers.compensationplan')),
            ],
            options={
                'db_table': 'compensation_plan_rates',
                'constraints': [models.UniqueConstraint(fields=('plan', 'lesson_type'), name='uniq_plan_lesson_type_rate')],
            },
        ),
        migrations.CreateModel(
            name='TeacherCompensationPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('month', models.CharField(max_length=7)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compensation_payments', to='schools.school')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compensation_payments', to='teachers.teacher')),
            ],
            options={
                'db_table': 'teacher_compensation_payments',
                'constraints': [models.UniqueConstraint(fields=('school', 'teacher', 'month'), name='uniq_teacher_month_payment')],
            },
        ),
        migrations.CreateModel(
            name='TeacherSchool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('compensation_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_links', to='teachers.compensationplan')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_links', to='schools.school')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_links', to='teachers.teacher')),
            ],
            options={
                'db_table': 'teacher_schools',
                'constraints': [models.UniqueConstraint(fields=('teacher', 'school'), name='uniq_teacher_school')],
            },
        ),
    ]
