# Generated by Django 5.2.7 on 2026-08-19 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachercompensationpayment',
            name='payment_method',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
