# Generated by Django 5.2.7 on 2026-09-07 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0003_teacher_first_name_teacher_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherschool',
            name='can_manage_bookings',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teacherschool',
            name='can_view_all_lessons',
            field=models.BooleanField(default=False),
        ),
    ]
