# Generated by Django 5.2.7 on 2026-08-19 12:02

import django.contrib.postgres.fields
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('address_line2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('province', models.CharField(blank=True, max_length=120)),
                ('country', models.CharField(blank=True, max_length=120)),
                ('website', models.CharField(blank=True, max_length=255)),
                ('vat_number', models.CharField(blank=True, max_length=60)),
                ('logo_url', models.TextField(blank=True)),
                ('active', models.BooleanField(default=False)),
                ('platform_fee_percentage', models.DecimalField(decimal_places=2, default=10, max_digits=5)),
                ('shop_commission_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('stripe_account_id', models.CharField(blank=True, max_length=255)),
                ('stripe_onboarding_complete', models.BooleanField(default=False)),
                ('grace_period_days', models.IntegerField(default=7)),
                ('free_trial_ends_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_policy_hours', models.IntegerField(default=24)),
                ('min_booking_notice_hours', models.IntegerField(default=2)),
                ('free_first_lesson', models.BooleanField(default=False)),
                ('show_teacher_to_students', models.BooleanField(default=True)),
                ('block_booking_on_documents', models.BooleanField(default=False)),
                ('ical_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_schools', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'schools',
            },
        ),
        migrations.CreateModel(
            name='SchoolClosure',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('type', models.CharField(choices=[('full_day', 'Full day'), ('partial', 'Partial')], default='full_day', max_length=20)),
                ('from_time', models.TimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='closures', to='schools.school')),
            ],
            options={
                'db_table': 'school_closures',
            },
        ),
        migrations.CreateModel(
            name='SchoolDocumentType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('code', models.CharField(max_length=60)),
                ('name', models.CharField(max_length=255)),
                ('variants', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=120), blank=True, default=list, size=None)),
                ('has_expiry', models.BooleanField(default=True)),
                ('required', models.BooleanField(default=False)),
                ('sort_order', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_types', to='schools.school')),
            ],
            options={
                'db_table': 'school_document_types',
            },
        ),
        migrations.CreateModel(
            name='SchoolLocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('google_maps_url', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='schools.school')),
            ],
            options={
                'db_table': 'school_locations',
            },
        ),
        migrations.CreateModel(
            name='SchoolMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_role', models.CharField(default='admin', max_length=40)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_memberships', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='schools.school')),
            ],
            options={
                'db_table': 'school_memberships',
            },
        ),
        migrations.CreateModel(
            name='SchoolRoom',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.CharField(max_length=255)),
                ('capacity', models.IntegerField(default=10)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='schools.schoollocation')),
            ],
            options={
                'db_table': 'school_rooms',
            },
        ),
        migrations.CreateModel(
            name='SchoolStudent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('free_lesson_used', models.BooleanField(default=False)),
                ('enrolled_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_links', to='schools.school')),
            ],
            options={
                'db_table': 'school_students',
            },
        ),
    ]
