# Generated by Django 5.2.7 on 2026-08-19 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolstudent',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_links', to='students.student'),
        ),
        migrations.AddConstraint(
            model_name='schoolclosure',
            constraint=models.UniqueConstraint(fields=('school', 'date'), name='uniq_school_closure_date'),
        ),
        migrations.AddConstraint(
            model_name='schooldocumenttype',
            constraint=models.UniqueConstraint(fields=('school', 'code'), name='uniq_school_doctype_code'),
        ),
        migrations.AddConstraint(
            model_name='schoolmembership',
            constraint=models.UniqueConstraint(fields=('profile', 'school'), name='uniq_school_membership'),
        ),
        migrations.AddConstraint(
            model_name='schoolstudent',
            constraint=models.UniqueConstraint(fields=('school', 'student'), name='uniq_school_student'),
        ),
    ]
