# Generated by Django 5.2.7 on 2026-08-19 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='language',
            field=models.CharField(default='it', max_length=8),
        ),
    ]
