# Generated by Django 5.2.7 on 2026-08-23 17:24

import django.contrib.postgres.fields
import django.utils.timezone
from django.db import migrations, models


# Seed dei ruoli base (matrice per Carlo: admin = tutto, staff = operatività
# didattica; sezioni = key della nav scuola). Modificabile solo da HQ.
ALL_SECTIONS = [
    "dashboard", "locations", "calendar", "courses", "lessons", "teachers",
    "compensation", "students", "packages", "payments", "documents", "inbox",
    "reports", "settings", "attendanceStatuses", "manualCredits", "team",
]
STAFF_SECTIONS = [
    "dashboard", "calendar", "courses", "lessons", "students", "documents",
    "inbox", "manualCredits",
]


def seed_roles(apps, schema_editor):
    SchoolRole = apps.get_model("schools", "SchoolRole")
    for key, label, perms in [
        ("owner", "Titolare", ALL_SECTIONS),
        ("admin", "Amministratore", ALL_SECTIONS),
        ("staff", "Staff", STAFF_SECTIONS),
    ]:
        SchoolRole.objects.get_or_create(key=key, defaults={"label": label, "builtin": True, "permissions": perms})


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0003_school_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolRole',
            fields=[
                ('key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=120)),
                ('builtin', models.BooleanField(default=False)),
                ('permissions', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=60), blank=True, default=list, size=None)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'school_roles',
            },
        ),
        migrations.RunPython(seed_roles, migrations.RunPython.noop),
    ]


