# Generated by Django 5.2.7 on 2026-09-14 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0006_backfill_school_owner_membership'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='show_available_spots_to_students',
            field=models.BooleanField(default=True),
        ),
    ]
