# Generated by Django 5.2.7 on 2026-09-16 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0007_school_show_available_spots_to_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolstudent',
            name='imported_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
