# Generated by Django 5.2.7 on 2026-09-19 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0008_schoolstudent_imported_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='nav_order',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
