# Generated by Django 5.2.7 on 2026-09-21 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0010_school_role_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolclosure',
            name='extends_packages',
            field=models.BooleanField(default=False),
        ),
    ]
