# Generated by Django 5.2.7 on 2026-10-06 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0012_schoolclosure_excluded_packages'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoollocation',
            name='directions',
            field=models.TextField(blank=True, default=''),
        ),
    ]
