# Generated by Django 5.2.7 on 2026-08-19 12:02

import django.contrib.postgres.fields
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=60)),
                ('type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed')], default='percentage', max_length=20)),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('minimum_order', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('valid_for', models.CharField(default='all', max_length=20)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('usage_count', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'discount_codes',
            },
        ),
        migrations.CreateModel(
            name='ShopOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('items', models.JSONField(blank=True, default=list)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('referral_discount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('shipping', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('stripe_payment_id', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(default='pending', max_length=20)),
            ],
            options={
                'db_table': 'shop_orders',
            },
        ),
        migrations.CreateModel(
            name='ShopProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(default='accessories', max_length=30)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('original_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('images', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, size=None)),
                ('colors', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=60), blank=True, default=list, size=None)),
                ('sizes', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=60), blank=True, default=list, size=None)),
                ('badges', models.JSONField(blank=True, default=list)),
                ('stripe_product_id', models.CharField(blank=True, max_length=255)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'shop_products',
            },
        ),
        migrations.CreateModel(
            name='ShopProductVariant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('size', models.CharField(blank=True, max_length=60)),
                ('color', models.CharField(blank=True, max_length=60)),
                ('stock', models.IntegerField(default=0)),
                ('sold', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'shop_product_variants',
            },
        ),
        migrations.CreateModel(
            name='ShopSale',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('qty', models.IntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('size', models.CharField(blank=True, max_length=60)),
                ('color', models.CharField(blank=True, max_length=60)),
                ('notes', models.TextField(blank=True)),
                ('order_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('shipping', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('online', 'Online')], default='manual', max_length=10)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('referrer', models.CharField(blank=True, max_length=255)),
                ('referrer_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('referrer_commission', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('commission', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payment_method', models.CharField(blank=True, max_length=30)),
            ],
            options={
                'db_table': 'shop_sales',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('type', models.CharField(choices=[('package', 'Package'), ('subscription', 'Subscription'), ('video', 'Video'), ('shop', 'Shop'), ('manual', 'Manual')], default='package', max_length=20)),
                ('product_id', models.UUIDField(blank=True, null=True)),
                ('product_name', models.CharField(blank=True, max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('currency', models.CharField(default='eur', max_length=8)),
                ('platform_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('school_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payment_method', models.CharField(default='stripe', max_length=30)),
                ('stripe_payment_id', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('pending', 'Pending'), ('refunded', 'Refunded'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('invoice_url', models.TextField(blank=True)),
                ('referral_commission', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'transactions',
            },
        ),
    ]
