# Generated by Django 5.2.7 on 2026-08-19 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commerce', '0001_initial'),
        ('schools', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountcode',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discount_codes', to='schools.school'),
        ),
        migrations.AddField(
            model_name='shoporder',
            name='referral_school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referred_shop_orders', to='schools.school'),
        ),
        migrations.AddField(
            model_name='shoporder',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shop_orders', to='schools.school'),
        ),
        migrations.AddField(
            model_name='shoporder',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shop_orders', to='students.student'),
        ),
        migrations.AddField(
            model_name='shopproduct',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shop_products', to='schools.school'),
        ),
        migrations.AddField(
            model_name='shopproductvariant',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='commerce.shopproduct'),
        ),
        migrations.AddField(
            model_name='shopsale',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='commerce.shopproduct'),
        ),
        migrations.AddField(
            model_name='shopsale',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shop_sales', to='students.student'),
        ),
        migrations.AddField(
            model_name='shopsale',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='commerce.shopproductvariant'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='referral_school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referred_transactions', to='schools.school'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='schools.school'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='students.student'),
        ),
        migrations.AddConstraint(
            model_name='discountcode',
            constraint=models.UniqueConstraint(fields=('school', 'code'), name='uniq_school_discount_code'),
        ),
    ]
