# Generated by Django 5.2.7 on 2026-08-20 02:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0002_initial'),
        ('schools', '0003_school_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopsale',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shop_sales', to='schools.school'),
        ),
    ]
