# Generated by Django 5.2.7 on 2026-08-24 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0003_shopsale_school'),
        ('schools', '0004_schoolrole'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountcode',
            name='max_uses',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='discountcode',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discount_codes', to='schools.school'),
        ),
        migrations.AlterField(
            model_name='discountcode',
            name='valid_for',
            field=models.CharField(choices=[('all', 'Everything'), ('packages', 'Packages'), ('subscriptions', 'Subscriptions'), ('shop', 'Shop')], default='all', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='discountcode',
            constraint=models.UniqueConstraint(condition=models.Q(('school__isnull', True)), fields=('code',), name='uniq_hq_discount_code'),
        ),
    ]
