# Generated by Django 5.2.7 on 2026-08-24 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0004_discountcode_max_uses_alter_discountcode_school_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountcode',
            name='applies_to',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
