# Generated by Django 5.2.7 on 2026-08-29 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0005_discountcode_applies_to'),
        ('schools', '0004_schoolrole'),
        ('students', '0005_student_first_name_student_last_name'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.UniqueConstraint(condition=models.Q(('stripe_payment_id', ''), _negated=True), fields=('stripe_payment_id',), name='uniq_transaction_stripe_payment_id'),
        ),
    ]
