# Generated by Django 5.2.7 on 2026-09-07 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0006_transaction_uniq_transaction_stripe_payment_id'),
        ('schools', '0006_backfill_school_owner_membership'),
        ('students', '0008_alter_studentdocument_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoporder',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='shoporder',
            index=models.Index(fields=['status', 'created_at'], name='shop_orders_status_created'),
        ),
    ]
