# Generated by Django 5.2.7 on 2026-08-19 12:02

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HQCountry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.CharField(max_length=120)),
                ('code', models.CharField(max_length=8)),
            ],
            options={
                'verbose_name_plural': 'HQ countries',
                'db_table': 'hq_countries',
            },
        ),
        migrations.CreateModel(
            name='HQCity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.CharField(max_length=120)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='geography.hqcountry')),
            ],
            options={
                'verbose_name_plural': 'HQ cities',
                'db_table': 'hq_cities',
            },
        ),
    ]
